### ISSUE TITLE
Specify the strategy for update in manifests

### ISSUE THREAD

**Issue by rasheedamir** [stakater/IngressMonitorController#116]
We must include the udpate strategy by default in all of the manifests e.g.

```
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

Also how many replica's should be run?
