### ISSUE TITLE
Handle per service monitoring

### ISSUE THREAD

**Issue by angel1st** [stakater/IngressMonitorController#135]
Hi there, I have a follow use case -  have Ingress controller installed and below is its sample resource file:

```
annotations:
   kubernetes.io/ingress.class: "nginx"
   monitor.stakater.com/enabled: "true"
Spec:
rules:
  - host: helloworld.awesome-customer.com
    http:
    paths:
    - path: /*
    backend:
    serviceName: helloworld
    servicePort: 8080
  - host: nextfineapp.awesome-customer.com
    http:
    paths:
    - path: /*
    backend:
    serviceName: nextfineapp
    servicePort: 8080
```

I would like to configure IMC with Pingdom as service provider. In this case IMC will monitor this particular Ingress controller. However, what I need is to receive notification in case particular service is down. So I need per service notification. How can I achieve that?
