### ISSUE TITLE
http2: No cached connection was available

### ISSUE THREAD

**Issue by majodev** [stakater/IngressMonitorController#213]
Hi,

We are seeing these error logs after running for a while (> 3days), requiring us to fully kill the pod so new monitors (UptimeRobot) are created again. Seems like, it's just looping around from there:

```bash
ingressmonitorcontroller-6596b57fc9-8cw8r ingressmonitorcontroller E1108 10:17:33.998586       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://<REMOVED_NODE_IP_FROM_LOG>:443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0: http2: no cached connection was available
ingressmonitorcontroller-6596b57fc9-8cw8r ingressmonitorcontroller E1108 10:17:34.998998       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://<REMOVED_NODE_IP_FROM_LOG>:443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0: http2: no cached connection was available
ingressmonitorcontroller-6596b57fc9-8cw8r ingressmonitorcontroller E1108 10:17:35.999415       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://<REMOVED_NODE_IP_FROM_LOG>:443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0: http2: no cached connection was available
ingressmonitorcontroller-6596b57fc9-8cw8r ingressmonitorcontroller E1108 10:17:37.010232       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://<REMOVED_NODE_IP_FROM_LOG>:443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0: http2: no cached connection was available
ingressmonitorcontroller-6596b57fc9-8cw8r ingressmonitorcontroller E1108 10:17:38.010687       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://<REMOVED_NODE_IP_FROM_LOG>:443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0: http2: no cached connection was available
ingressmonitorcontroller-6596b57fc9-8cw8r ingressmonitorcontroller E1108 10:17:39.011058       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: Get https://<REMOVED_NODE_IP_FROM_LOG>:443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0: http2: no cached connection was available
```

**Comment by usamaahmadkhan** [comment]
Hi @majodev , Can you tell which k8s version are you using and what are your configurations?

**Comment by majodev** [comment]
v1.14.7-gke.10

```yaml
# configmap
    providers:
    - name: UptimeRobot
      apiKey: <REDACTED>
      apiURL: https://api.uptimerobot.com/v2/
      alertContacts: <REDACTED>
    enableMonitorDeletion: false
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
    resyncPeriod: 0
    creationDelay: 0

# deployment
    - env:
    - name: CONFIG_FILE_PATH
        value: /etc/IngressMonitorController/config.yaml
    - name: LOG_LEVEL
        value: info
    - name: LOG_FORMAT
        value: text
```
