### ISSUE TITLE
Invalid application key error even though it's correct - Pingdom

### ISSUE THREAD

**Issue by tomjohnburton** [stakater/IngressMonitorController#214]
Am I doing something stupid here...? 
This is my config map set up

```
data:
  config.yaml: |-
    providers:
    - name: Pingdom
      apiKey: fdjsfhksdnskfjNOTREALAPIKEYndkjsbfskdjdf
      apiURL: https://api.pingdom.com/
      username: my-email
      password: my-password
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
    # how often (in seconds) monitors should be synced to their Kubernetes resources (0 = disabled)
    resyncPeriod: 0
    # creationDelay is a duration string to add a delay before creating new monitor (e.g., to allow DNS to catch up first)
    # https://golang.org/pkg/time/#ParseDuration
    creationDelay: 0
```

Just constantly fails with `msg="Error received while listing checks:  403 Forbidden: Invalid application key"
`
