### ISSUE TITLE
GetByName Request failed for name

### ISSUE THREAD

**Issue by jseiser** [stakater/IngressMonitorController#220]
I am unable to get this to work, asked in slack and was told to post a bug here.  

HelmRelease
```
     ingressMonitorController:
      image:
        name: stakater/ingressmonitorcontroller
        tag: 1.0.47
      providers:
        - name: UptimeRobot
          apiKey: u525902-key-here71a0
          apiURL: https://api.uptimerobot.com/v2
          alertContacts: "2908284_0_0"
      enableMonitorDeletion: true
      configFilePath: /etc/IngressMonitorController/config.yaml
      monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
```

Image
`image: stakater/ingressmonitorcontroller:1.0.47`

Container
```
# cat /etc/IngressMonitorController/config.yaml
providers:
- name: UptimeRobot
  apiKey: u525902-key-here763471a0
  apiURL: https://api.uptimerobot.com/v2
  username: null
  password: null
  alertContacts: 2908284_0_0
enableMonitorDeletion: true
monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"

```

I can hit the Ingress from the container

```
wget http://fakecustomer1.domain.com/arms/ws/rest/status/hzActive
Connecting to fakecustomer1.domaincom (IP:80)
hzActive             100% |*********************************************************************************************************************************************************************************************|     2   0:00:00 ETA
/ # 
```

Logs
```
2019/12/06 21:31:33 Monitor Name: fakecustomer1.domaincom
2019/12/06 21:31:33 Monitor URL: http://fakecustomer1.domain.com/arms/ws/rest/status/hzActive
2019/12/06 21:31:33 GetByName Request failed for name: fakecustomer1.domain.com. Status Code: 404
2019/12/06 21:31:33 AddMonitor Request failed. Status Code: 404
```
The API key works.

```
curl -d "api_key=u525902-thatkey1a0" -X POST https://api.uptimerobot.com/v2/getAlertContacts | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   936  100   896  100    40   3234    144 --:--:-- --:--:-- --:--:--  3366
{
  "stat": "ok",
```

Ingress Annotation
```
      monitor.stakater.com/enabled: "true"
      monitor.stakater.com/name: fakecustomer1.domain.com

```

Im really at a loss for what else to look at.
