### ISSUE TITLE
How to handle in the case only ingress path configured 

### ISSUE THREAD

**Issue by ehdieunguyen** [stakater/IngressMonitorController#255]
Hi, I am trying to apply this project to our k8s cluster, and integrate with Pingdom. 
I have a case need your help, it likes the following:

```
# ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: devops
  annotations:
    monitor.stakater.com/enabled: "true"
spec:
  rules:
  - http:
      paths:
      - path: /podinfo
        backend:
          serviceName: podinfo
          servicePort: 8989
```

and in the ingress monitor controller pod logs

```
time="2020-06-03T13:02:00Z" level=info msg="Monitor URL: http:///podinfo"
time="2020-06-03T13:02:00Z" level=info msg="Error received while listing checks:  403 Forbidden: "
time="2020-06-03T13:02:00Z" level=info msg="strconv.Atoi: parsing \"0544483_0_0\": invalid syntax"
time="2020-06-03T13:02:00Z" level=info msg="strconv.Atoi: parsing \"91166,10924\": invalid syntax"
time="2020-06-03T13:02:00Z" level=info msg="Error Adding Monitor:  Invalid value for `Hostname`.  Must contain non-empty string"
^[[Ctime="2020-06-03T14:26:24Z" level=info msg="Error received while listing checks:  403 Forbidden: "
```

I tried to read the documentation but I don't found any guides to help me resolve this problem.
So, does anyone know, pls give me some help. Many thanks.
