### ISSUE TITLE
GetByName Request failed - Status Code: 404

### ISSUE THREAD

**Issue by dicolasi** [stakater/IngressMonitorController#285]
I am using the following chart 
```
- name: ingressmonitorcontroller
  repository: https://stakater.github.io/stakater-charts/
  version: 1.0.101
```
with the following configuration: 
```
ingressmonitorcontroller:
  ingressMonitorController:
    watchNamespace: jx-production
    data:
      config.yaml: |-
        providers:
        - name: UptimeRobot
          apiKey: vault:uptime-robot:main-api-key
          apiURL: https://api.uptimerobot.com/v2

```

However, got the following error from the pod: 

```
WARNING: Found newest pod: ingressmonitorcontroller-744df9899b-dw78p
time="2020-10-14T11:06:30Z" level=info msg="Reading YAML Configuration/etc/IngressMonitorController/config.yaml"
time="2020-10-14T11:06:30Z" level=info msg="Starting Ingress Monitor controller"
time="2020-10-14T11:06:30Z" level=info msg="Monitor Name: auth-jx-production"
time="2020-10-14T11:06:30Z" level=info msg="Monitor URL: https://auth-jx-production.property.xyz/auth/realms/master"
time="2020-10-14T11:06:30Z" level=info msg="GetByName Request failed for name: auth-jx-production. Status Code: 404"
time="2020-10-14T11:06:30Z" level=info msg="AddMonitor Request failed. Status Code: 404"
2020/10/14 11:06:30 Pod has 2 containers so skipping health endpoint
time="2020-10-14T11:06:30Z" level=info msg="Monitor Name: docs-jx-production"
time="2020-10-14T11:06:30Z" level=info msg="Monitor URL: https://docs-jx-production.property.xyz"
time="2020-10-14T11:06:31Z" level=info msg="GetByName Request failed for name: docs-jx-production. Status Code: 404"
time="2020-10-14T11:06:31Z" level=info msg="AddMonitor Request failed. Status Code: 404"
2020/10/14 11:06:31 Pod has 2 containers so skipping health endpoint
time="2020-10-14T11:06:31Z" level=info msg="Monitor Name: platform-frontend-jx-production"
time="2020-10-14T11:06:31Z" level=info msg="Monitor URL: https://property.xyz"
time="2020-10-14T11:06:31Z" level=info msg="GetByName Request failed for name: platform-frontend-jx-production. Status Code: 404"
time="2020-10-14T11:06:31Z" level=info msg="AddMonitor Request failed. Status Code: 404"
2020/10/14 11:06:31 Pod has 2 containers so skipping health endpoint
time="2020-10-14T11:06:31Z" level=info msg="Monitor Name: test-name"
time="2020-10-14T11:06:31Z" level=info msg="Monitor URL: https://www.property.xyz"
time="2020-10-14T11:06:31Z" level=info msg="GetByName Request failed for name: test-name. Status Code: 404"
time="2020-10-14T11:06:31Z" level=info msg="AddMonitor Request failed. Status Code: 404"
2020/10/14 11:11:57 Pod has 2 containers so skipping health endpoint
time="2020-10-14T11:11:57Z" level=info msg="Monitor Name: platform-frontend-jx-production"
time="2020-10-14T11:11:57Z" level=info msg="Monitor URL: https://property.xyz"
time="2020-10-14T11:11:57Z" level=info msg="GetByName Request failed for name: platform-frontend-jx-production. Status Code: 404"
time="2020-10-14T11:11:57Z" level=info msg="AddMonitor Request failed. Status Code: 404"
2020/10/14 11:11:57 Pod has 2 containers so skipping health endpoint
time="2020-10-14T11:11:57Z" level=info msg="Monitor Name: test-name"
time="2020-10-14T11:11:57Z" level=info msg="Monitor URL: https://www.property.xyz"
time="2020-10-14T11:11:57Z" level=info msg="GetByName Request failed for name: test-name. Status Code: 404"
time="2020-10-14T11:11:57Z" level=info msg="AddMonitor Request failed. Status Code: 404"
2020/10/14 11:31:14 Pod has 2 containers so skipping health endpoint
time="2020-10-14T11:31:14Z" level=info msg="Monitor Name: test-name"
time="2020-10-14T11:31:14Z" level=info msg="Monitor URL: https://www.property.xyz"
time="2020-10-14T11:31:14Z" level=info msg="GetByName Request failed for name: test-name. Status Code: 404"
time="2020-10-14T11:31:14Z" level=info msg="AddMonitor Request failed. Status Code: 404"

```

Basically, every ingress returns 404, which is never the case. Am I missing something?

**Comment by namm2** [comment]
@dicolasi It seems like Pingdom removed support for API version 2, could you create a new Pingdom token, upgrade to v1.0.103 then update configs to below? 

```
ingressmonitorcontroller:
  ingressMonitorController:
    watchNamespace: jx-production
    data:
      config.yaml: |-
        providers:
        - name: UptimeRobot
          apiToken: abcxyz123456
```

It seems like I forgot to update the main README.
