### ISSUE TITLE
RBAC usage should be minimal

### ISSUE THREAD

**Issue by cwrau** [stakater/IngressMonitorController#328]
Currently, the charts `role.yaml` (https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/templates/role.yaml) requests way too many permissions.

The only two I can understand are the ones for ingresses and endpoint monitors. I guess maybe `route.openshift.io`, I don't exactly know what that is.

The other ones shouldn't be needed, right?

Additionally, the controller tries to request disallowed resources; 

```
pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:monitoring:monitoring-ingress-monitor-operator" cannot list resource "services" in API group "" at the cluster scope
```

As I understand it, that should be removed as it's not needed.

**Comment by cwrau** [comment]
Also, the `create`, `delete`, `patch` and `update` permissions on enpointmonitors shouldn't be needed' either

**Comment by ahmedwaleedmalik** [comment]
Hi @cwrau,

I upgraded the operator to the latest `operator-sdk` version so might have missed out on something.

- `route.openshift.io` is required, it's an openshift alternative for ingress
- rbac for `deployment, statefulsets, daemonsets, replicasets` is also required because they are used internally to compute health endpoint for a route or ingress
- The access needs to be added, not removed for `services`
- Regarding `enpointmonitors` the operator owns those resources and will `patch, get, list, update` the resource. Not sure if `create` or `delete` are required

Please check: https://github.com/stakater/IngressMonitorController/blob/master/pkg/kube/wrappers/ingress-wrapper.go#L128

**Comment by ahmedwaleedmalik** [comment]
Currently, I won't have the bandwidth to work on this but if you can remove the redundant RBAC that would be much appreciated.

**Comment by cwrau** [comment]
So you go via the ingress to the service, then by its labelSelector to the pods. Then you get its readiness probe

Then why do you need deployment and such? In the podSpec is everything regarding their healthChecks, that's how you build the health endpoint in the code you mentioned anyways.

Ok, so I understand the requirement for service and pods

I adjusted the ClusterRole, the following seems to work;

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
rules:
- apiGroups:
  - endpointmonitor.stakater.com
  resources:
  - endpointmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - endpointmonitor.stakater.com
  resources:
  - endpointmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - endpointmonitor.stakater.com
  resources:
  - endpointmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
```
