### ISSUE TITLE
Statuscake - contactGroup always empty when creating tests

### ISSUE THREAD

**Issue by sgasquet** [stakater/IngressMonitorController#371]
Hey there !

I am facing an issue using this IngressMonitorController with StatusCake.
Following this documentation :
https://github.com/stakater/IngressMonitorController/blob/master/docs/statuscake-configuration.md

I tried IDs, name, string, array of string, the ContactGroup is never defined and the automatically created tests are always with empty contactGroup.
Is there anything i am missing in my configuration ?

What i am applying : 
`
providers:
  - name: StatusCake
    contactGroup: 123456
    apiKey: fXXXXXXXXXXXXXXXXR
    apiURL: https://app.statuscake.com/API/
    username: myusername
enableMonitorDeletion: true
`

If anyone managed to make this part working, any help would be useful :)

**Comment by GeorgFleig** [comment]
Hi @sgasquet, the contact group configuration is part of the `EndpointMonitor` object, not the generic IMC configuration.

See https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/crds/endpointmonitor.stakater.com_endpointmonitors.yaml#L137 or https://github.com/stakater/IngressMonitorController/blob/master/docs/statuscake-configuration.md

The contact group must be the ID of the group as a string. Example:

```
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: test
spec:
  forceHttps: true
  url: https://google.com
  providers: "StatusCake"
  statusCakeConfig:
    checkRate: 300
    contactGroup: "123456"
```
