### ISSUE TITLE
uptimerobots default interval not configureable in config.yaml

### ISSUE THREAD

**Issue by benedikt-bartscher** [stakater/IngressMonitorController#425]
currently only the apiKey, url, alertContacts and statusPage can be set for uptimerobot in config.yaml. Setting a default interval of for example 60s does not work.

```
providers: 
  - name: UptimeRobot
    apiKey: ******
    apiURL: https://api.uptimerobot.com/v2/
    alertContacts: "*****"
    interval: 60
enableMonitorDeletion: true
resyncPeriod: 60
creationDelay: 120
```
