### ISSUE TITLE
[StatusCake Support] Stuck at Starting Ingress Monitor controller

### ISSUE THREAD

**Issue by valentin2105** [stakater/IngressMonitorController#45]
Hi,

Good work for IngressMonitor, 

I'm a StatusCake user, so I created an API key, and deployed configmap, rbac and Deployment of IngressMonitorController v1.0.6,

```
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: ingressmonitorcontroller
    version: 1.0.6
    group: com.stakater.platform
    provider: stakater
    chart: "IngressMonitorController-1.0.6"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: <myKEY>
      apiURL: https://app.statuscake.com/API/
      alertContacts: Principal
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
```

Small problem, 

It start and stuck at `Starting Ingress Monitor controller` ... 

So I think, I need to create an annotation for my ingresses now, and it doesn't change anything. 

Thanks for debuging this with me. 

(I work in IPv6 environment.)
