### ISSUE TITLE
Ingressmonitorcontroller experiences GO panic, restarts

### ISSUE THREAD

**Issue by ShawnUCD** [stakater/IngressMonitorController#450]
Hello,
I'm running v2.1.28, but have had this issue with 2.1.26 and 2.1.27 as well.  I'm running IMC config in Kubernetes 1.25 (AWS EKS):

```
# https://github.com/stakater/IngressMonitorController/tree/master/deployments/kubernetes/chart/ingressmonitorcontroller
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressmonitorcontroller
  namespace: monitoring
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ingressmonitorcontroller
      version: 2.1.28
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: monitoring
  values:
    namespace: monitoring
    watchNamespaces: ""
---
```
Below this block in the deployment yaml, I have the [crds](https://github.com/stakater/IngressMonitorController/blob/master/config/crd/bases/endpointmonitor.stakater.com_endpointmonitors.yaml) defined, but didn't think that was relevant enough to include here.  Those CRDs are up-to-date for v2.1.28.

I'm using the following secret:

```
providers:
- name: StatusCake
  username: ourUsername
  apiKey: ourAPIKey
  apiURL: https://api.statuscake.com/v1/uptime
  alertContacts: ourcontactid
enableMonitorDeletion: true
monitorNameTemplate: "{{.Name}}-prod"
```

For each uptime check, we have an `endpointmonitor` resource defined.  This is defined inline in the app's deployment yaml in our repo.

Example `endpointmonitor` resource from app yaml:
```
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: ourapplication
  namespace: apps
spec:
  forceHttps: true
  url: https://app.ourdomain.com/ourapplication/healthz
  statusCakeConfig:
    testTags: "env-prod,app-ourapplication,test-v2"
    checkRate: 60
---
```

I will see an error similar to the following frequently, just before the `ingressmonitorcontroller` pod restarts:

```
{"level":"info","ts":1681401077.4984636,"logger":"statuscake-monitor","msg":"Monitor Updated: 6805245"}
{"level":"info","ts":1681401078.5584974,"logger":"statuscake-monitor","msg":"Monitor Updated: 6805228"}
{"level":"info","ts":1681401079.67445,"logger":"statuscake-monitor","msg":"Monitor Updated: 6805242"}
{"level":"info","ts":1681401081.1455305,"logger":"statuscake-monitor","msg":"Monitor Updated: 6805248"}
{"level":"info","ts":1681401082.182257,"logger":"statuscake-monitor","msg":"Monitor Updated: 6805243"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x148f4a3]

goroutine 158 [running]:
github.com/stakater/IngressMonitorController/v2/pkg/monitors/statuscake.(*StatusCakeMonitorService).GetAll(0xfff9f0b0b2c6fba9?)
  /workspace/pkg/monitors/statuscake/statuscake-monitor.go:294 +0x83
github.com/stakater/IngressMonitorController/v2/pkg/monitors/statuscake.(*StatusCakeMonitorService).GetByName(0x0?, {0xc0006b9b50, 0x9})
  /workspace/pkg/monitors/statuscake/statuscake-monitor.go:230 +0x2a
github.com/stakater/IngressMonitorController/v2/pkg/monitors.(*MonitorServiceProxy).GetByName(...)
  /workspace/pkg/monitors/monitor-proxy.go:84
github.com/stakater/IngressMonitorController/v2/pkg/controllers.findMonitorByName({{0xc0004dc0f0, 0xa}, {0x1ac1c48, 0xc0000980a0}}, {0xc0006b9b50?, 0xc0006a3a30?})
  /workspace/pkg/controllers/endpointmonitor_util.go:10 +0x42
github.com/stakater/IngressMonitorController/v2/pkg/controllers.(*EndpointMonitorReconciler).Reconcile(0xc0000980f0, {0xc0006cd3e0?, 0x163ccc0?}, {{{0xc0006a3a34, 0x4}, {0xc0006a3a30, 0x4}}})
  /workspace/pkg/controllers/endpointmonitor_controller.go:88 +0x4a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00042e160, {0x1abe518, 0xc0006cd3e0}, {{{0xc0006a3a34?, 0x1789b00?}, {0xc0006a3a30?, 0x4041f4?}}})
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x27e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00042e160, {0x1abe470, 0xc000164540}, {0x16a5b40?, 0xc0001bae60?})
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x349
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00042e160, {0x1abe470, 0xc000164540})
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
  /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x31c
```

This seems to happen randomly, and after a period where IMC is functioning as expected.  The pod then restarts, and it resumes functioning normally, up until it randomly fails again with a Go panic.  

I hope I've included all relevant config and logs here, but please let me know if not and I'll update the description.  

**Attempted solutions**
Added/removed Newline at the end of the secret
Verified URL for Statuscake API
Downgraded to v2.1.27, v2.1.26
Updated CRDs to include additions for v2.1.28 (statuscake string match)
Looked for pattern in which uptime check appears before each crash (different every time)
