### ISSUE TITLE
missing global.labels in pods

### ISSUE THREAD

**Issue by Boeller666** [stakater/IngressMonitorController#519]
We need to set some labels by default to our deployments/pods.  

`global.labels` does not attach these labels to the pods.

Please add 
```
{{- if .Values.global.labels }}
{{ toYaml .Values.global.labels }}
{{- end }}
```
to the [deployment.yaml](https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/templates/deployment.yaml#L20) or create another `podLabels` helper method that includes the global labels.

**Comment by nohant** [comment]
The chart at version 2.1.38, with this values.yml
```
global:
  labels:
    app: ingressmonitorcontroller
```
generates this kind of configuration inside the deployment:
```
monitoring, ingressmonitorcontroller, Deployment (apps) has changed:
  # Source: ingressmonitorcontroller/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ingressmonitorcontroller
    namespace: monitoring
    labels:
      helm.sh/chart: ingressmonitorcontroller-2.1.38
      app.kubernetes.io/name: ingressmonitorcontroller
      app.kubernetes.io/instance: ingress-monitor-controller
      app.kubernetes.io/version: "2.1.38"
      app.kubernetes.io/managed-by: helm
+     app: ingressmonitorcontroller
      control-plane: controller-manager
```

due to the configuration in the file helpers.
@Boeller666 you instead need the spec.template.labels?

```
    template:
      metadata:
        labels:
          app.kubernetes.io/name: ingressmonitorcontroller
          app.kubernetes.io/instance: ingress-monitor-controller
+         app: ingressmonitorcontroller
      spec:
```
