### ISSUE TITLE
StatusCake nodeLocations are not configured

### ISSUE THREAD

**Issue by tibuntu** [stakater/IngressMonitorController#540]
**Describe the bug**
In the past I was able to configure test locations for StatusCake using `nodeLocations` in the spec of the endpointmonitor.
However, we deployed a couple of new endpointmonitors and the locations are not set anymore.

**To Reproduce**
Deploy a `EndpointMonitor` with a `statusCakeConfig`:

```yaml
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: statuscake-test
  namespace: default
spec:
  forceHttps: true
  statusCakeConfig:
    basicAuthUser: myUser
    checkRate: 300
    confirmation: 1
    enableSslAlert: true
    followRedirect: true
    nodeLocations: frankfurt,amsterdam,stockholm
    paused: false
    port: 443
    realBrowser: true
    statusCodes: 401,404,500,502,503
    testTags: cloud
    testType: HTTP
    triggerRate: 1
  url: https://some-url.my-domain.com/
```

**Expected behavior**
The check is created in statuscake and the locations are selected as in the spec.

**Environment**
 - Operator Version:  v2.1.38
 - Kubernetes Version: v1.24.17
