### ISSUE TITLE
Produces double-slashes in uptime URL

### ISSUE THREAD

**Issue by sodenjtef** [stakater/IngressMonitorController#57]
The IngressMonitorController seems to append an extra slash into the URL.

If the health endpoint of an pod is set to `/myapp/health` and the path of a corresponding ingress is set to '/', the final requested URL contains two slashes: `https://example.com//myapp/health`.

This breaks at least modern spring applications (they return http 500 with "The request was rejected because the URL was not normalized.").

A workaround is to specify the ingress without `path: /`.

**Comment by hazim1093** [comment]
Hi @sodenjtef , 

Can you share what your ingress looks like which causes the bug?

**Comment by sodenjtef** [comment]
@hazim1093 Thanks for looking at the issue.

My ingress which leads to the issue looks like:

``` 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapplication
  annotations:
    kubernetes.io/tls-acme: "true"
    monitor.stakater.com/enabled: "true"
spec:
  tls:
  - hosts:
    - 'myapplication.example.org'
  rules:
  - host: 'myapplication.example.org'
    http:
      paths:
      - backend:
          serviceName: 'myapplication'
          servicePort: 8080
        path: /
```

Without the line `path: /`, there are no double slashes.
 
The issue could probably be solved by using something like https://stackoverflow.com/a/43415988/1182783 in ingress-wrapper.go getURL() to join the healthEndpoint path with the subpath url instead of simple concatenating url parts.
