### ISSUE TITLE
[ENHANCE] Allow configuring annotations for Deployment

### ISSUE THREAD

**Issue by dennis-ge** [stakater/IngressMonitorController#574]
**Is your feature request related to a problem? Please describe.**
I would like to use the [stakater Reloader](https://github.com/stakater/Reloader) in combination with the IngressMonitorController to automatically restart the IngressMonitorController deployment as soon as a secret is updated. The reason I would like to have this functionality is that I use a secret in the [envFrom](https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/values.yaml#L101) section of the deployment, but when the secret is updated with new information a restart is necessary for the controller to read the new data. 

As per [How To Use Reloader](https://github.com/stakater/Reloader?tab=readme-ov-file#how-to-use-reloader), an annotation on the deployment is necessary so that the reloader controller can restart the deployment. 

**Describe the solution you'd like**
I would like to make the annotations of the deployment configurable in the helm chart. There is already `podAnnotations` so I would propose `deploymentAnnotations`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingress-monitor-controller.fullname" . }}
  namespace: {{ include "ingress-monitor-controller.namespace" . }}
{{- with .Values.deploymentAnnotations }}
   annotations:
   {{- toYaml . | nindent 4 }}
{{- end }}
...
```

**Describe alternatives you've considered**
I am also open for other names/ways to realize this, it doesn't have to be `deploymentAnnotations`.

**Additional context**
I can also provide a PR if wanted.
